// Auto-generated by Supabase CLI (or stub for development)
// This file contains TypeScript types generated from your Supabase schema

export interface Database {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, any>
        Insert: Record<string, any>
        Update: Record<string, any>
      }
      loes_certificates: {
        Row: {
          id: string
          horse_id: string
          tipo_hemorragia: string
          descripcion: string | null
          fecha_deteccion: string
          detectado_por_vet_id: string
          detectado_por_vet_nombre: string
          estado: string
          created_at: string
        }
        Insert: Record<string, any>
        Update: Record<string, any>
      }
    }
    Views: Record<string, any>
    Functions: Record<string, any>
    Enums: Record<string, any>
  }
}
