-- Create treatment_report_item_codes junction table
CREATE TABLE IF NOT EXISTS treatment_report_item_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  treatment_report_id UUID NOT NULL REFERENCES treatment_reports(id) ON DELETE CASCADE,
  catalog_item_id UUID NOT NULL REFERENCES catalog_items(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(treatment_report_id, catalog_item_id)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_treatment_report_item_codes_treatment_report_id
  ON treatment_report_item_codes(treatment_report_id);
CREATE INDEX IF NOT EXISTS idx_treatment_report_item_codes_catalog_item_id
  ON treatment_report_item_codes(catalog_item_id);

-- Enable RLS
ALTER TABLE treatment_report_item_codes ENABLE ROW LEVEL SECURITY;

-- RLS policies
CREATE POLICY "authenticated_select_treatment_report_item_codes"
  ON treatment_report_item_codes FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "authenticated_insert_treatment_report_item_codes"
  ON treatment_report_item_codes FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "authenticated_update_treatment_report_item_codes"
  ON treatment_report_item_codes FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "authenticated_delete_treatment_report_item_codes"
  ON treatment_report_item_codes FOR DELETE
  TO authenticated
  USING (true);

-- Insert 750+ item codes from EALLC 2025-2026 Item Master List into catalog_items
INSERT INTO catalog_items (category, name, active, sort_order) VALUES
('item_code', 'VABD — ABDOMINAL BANDAGE', true, 1),
('item_code', 'CABC — ABDOMINOCENTESIS', true, 2),
('item_code', 'IACE — ACEPROMACINA 50ML / 1CC', true, 3),
('item_code', 'IADN — ADENOSINE INJECTION', true, 4),
('item_code', 'IADE — ADEQUAN 5CC', true, 5),
('item_code', 'ADMF — ADMITION FEE', true, 6),
('item_code', 'I7Y3 — ADRENAL CORTEX - ADENOSINE CO', true, 7),
('item_code', 'IADR — ADRENAL CORTEX INJ', true, 8),
('item_code', 'IAMYF — AMIGLYDE 2CC', true, 9),
('item_code', 'UIAK — AMIKACIN INFUSION UTERINE', true, 10),
('item_code', 'AAPF — AMINOAXIN INJECTION PASO FINO', true, 11),
('item_code', 'AATX — AMINOAXIN TREATMENT', true, 12),
('item_code', 'AHSTX — ANABOLIC HEMOSTRIMULANT TX', true, 13),
('item_code', 'ANES 2 — ANESTECIA', true, 14),
('item_code', 'EPID — ANESTECIA EPIDURAL', true, 15),
('item_code', 'ANES — ANESTHESIA', true, 16),
('item_code', 'FALDC — ANGULAR LIMB DEFORMITY FOOT TR', true, 17),
('item_code', 'AHAP — ANHYDROSIS ACUPUNCTURE', true, 18),
('item_code', 'SALD — ANULAR LIGAMENT DESMOTOMY', true, 19),
('item_code', 'TAPS — ARTHROCENTECIS', true, 20),
('item_code', 'SIFA — ARTHRODESIS CUARTILLA', true, 21),
('item_code', 'SMFA — ARTHRODESIS MENUDILLO', true, 22),
('item_code', 'ARGM — ARTHROGRAM', true, 23),
('item_code', 'ARTH — ARTHROSCOPIA', true, 24),
('item_code', 'ART2 — ARTHROSCOPY 2 JOINTS', true, 25),
('item_code', 'ART3 — ARTHROSCOPY 3 JOINTS', true, 26),
('item_code', 'ATTC — ARTHROTOMY TARSOCRURAL JOINT', true, 27),
('item_code', 'AINS — ARTIFICIAL INSEMINATION', true, 28),
('item_code', 'ART4 — ARTYR0SC0PY 4 JOINTS', true, 29),
('item_code', 'GASX — ARYTENODECTOMY SURGERY', true, 30),
('item_code', 'OATP — ATP PASTE', true, 31),
('item_code', 'IDEX — AZIUM', true, 32),
('item_code', 'IBBF — B-12 & B- COMPLEX VIT. INJ.', true, 33),
('item_code', 'IAD5 — B-15 AND ADENOSINE INJ', true, 34),
('item_code', 'BBAC — BACK CHEMICAL ACUPUNTURE', true, 35),
('item_code', 'BBACRC — BACK CHEMICAL ACUPUNTURE', true, 36),
('item_code', 'IBANLD — BANAMINA LOW DOSE', true, 37),
('item_code', 'IBAN — BANAMINE 10CC', true, 38),
('item_code', 'IBAF — BANAMINE FOR FOALS', true, 39),
('item_code', 'IBNL — BANAMINE LOW DOSE', true, 40),
('item_code', 'BAND2 — BANDAGE CHANGE', true, 41),
('item_code', 'VHED — BANDAGE HEAD', true, 42),
('item_code', 'VLEL — BANDAGE LEFT ELBOW', true, 43),
('item_code', 'VLFD — BANDAGE LEFT FRONT DISTAL LIMB', true, 44),
('item_code', 'VLFH — BANDAGE LEFT FRONT FOOT', true, 45),
('item_code', 'VLFL — BANDAGE LEFT FRONT FULL LEG', true, 46),
('item_code', 'VLFP — BANDAGE LEFT FRONT PROX. LIMB', true, 47),
('item_code', 'VLHD — BANDAGE LEFT HIND DISTAL LIMB', true, 48),
('item_code', 'VLHH — BANDAGE LEFT HIND FOOT', true, 49),
('item_code', 'VLHL — BANDAGE LEFT HIND FULL LEG', true, 50),
('item_code', 'VLHP — BANDAGE LEFT HIND PROX. LIMB', true, 51),
('item_code', 'VLHO — BANDAGE LEFT HOCK', true, 52),
('item_code', 'VLKN — BANDAGE LEFT KNEE', true, 53),
('item_code', 'VNCK — BANDAGE NECK', true, 54),
('item_code', 'BAND1 — BANDAGE PLACEMENT', true, 55),
('item_code', 'VRKN — BANDAGE RICHT KNEE', true, 56),
('item_code', 'VRAB — BANDAGE RIGHT ANTERBRACHIUM', true, 57),
('item_code', 'VREL — BANDAGE RIGHT ELBOW', true, 58),
('item_code', 'VRFD — BANDAGE RIGHT FRONT DISTAL LIM', true, 59),
('item_code', 'VRFH — BANDAGE RIGHT FRONT FOOT', true, 60),
('item_code', 'VRFL — BANDAGE RIGHT FRONT FULL LEG', true, 61),
('item_code', 'VRFP — BANDAGE RIGHT FRONT PROX. LIMB', true, 62),
('item_code', 'VRHD — BANDAGE RIGHT HIND DISTAL LIMB', true, 63),
('item_code', 'VRHH — BANDAGE RIGHT HIND FOOT', true, 64),
('item_code', 'VRHL — BANDAGE RIGHT HIND FULL LEG', true, 65),
('item_code', 'VRHP — BANDAGE RIGHT HIND PROX. LIMB', true, 66),
('item_code', 'VRHO — BANDAGE RIGHT HOCK', true, 67),
('item_code', 'VRMV — BANDANGE REMOVAL', true, 68),
('item_code', 'IBAC — BAYTRIL 30CC', true, 69),
('item_code', 'OBCAA — BCAA PASTE TREATMENT', true, 70),
('item_code', 'IBBE — B-COMPLEX, B-12 INJECTION', true, 71),
('item_code', 'IBBC — B-COMPLEX, C COPPER, B-12', true, 72),
('item_code', 'JBBC — B-COMPLEX, C COPPER, B-12 JUG', true, 73),
('item_code', 'NGBS — BIOSPONGE POWDER NASOGASTRIC', true, 74),
('item_code', 'IB40 — BLEEDING 40 TX 10CC DOSIS', true, 75),
('item_code', 'BSSH — BLOCK BOTH FRONT SHIN', true, 76),
('item_code', 'BDBN — BLOCK DEEP BRANCH', true, 77),
('item_code', 'BFFT — BLOCK FRONT FEET', true, 78),
('item_code', 'BHFT — BLOCK HIND FEET', true, 79),
('item_code', 'BH01 — BLOCK HOCKS', true, 80),
('item_code', 'BK01 — BLOCK KNEES', true, 81),
('item_code', 'BLFX — BLOCK LEFT FRONT ABAXIAL', true, 82),
('item_code', 'VLFX — BLOCK LEFT FRONT ABAXIAL', true, 83),
('item_code', 'BLFA — BLOCK LEFT FRONT ANKLE', true, 84),
('item_code', 'BLFH — BLOCK LEFT FRONT FOOT', true, 85),
('item_code', 'BLFV — BLOCK LEFT FRONT HIGH VOLAR', true, 86),
('item_code', 'BLF4 — BLOCK LEFT FRONT LOW 4', true, 87),
('item_code', 'BLFD — BLOCK LEFT FRONT PALMAR DIGITA', true, 88),
('item_code', 'BLFP — BLOCK LEFT FRONT PASTER', true, 89),
('item_code', 'BLFR — BLOCK LEFT FRONT RING BLOCK', true, 90),
('item_code', 'BLFS — BLOCK LEFT FRONT SHIN', true, 91),
('item_code', 'BLFT — BLOCK LEFT FRONT TENDON', true, 92),
('item_code', 'BLHX — BLOCK LEFT HIND ABAXIAL', true, 93),
('item_code', 'BLHA — BLOCK LEFT HIND ANKLE', true, 94),
('item_code', 'BLHF — BLOCK LEFT HIND FOOT', true, 95),
('item_code', 'BLH4 — BLOCK LEFT HIND LOW 4', true, 96),
('item_code', 'BLHD — BLOCK LEFT HIND PLANTAR DIGITA', true, 97),
('item_code', 'BLHR — BLOCK LEFT HIND RING BLOCK', true, 98),
('item_code', 'BLHH — BLOCK LEFT HOCK', true, 99),
('item_code', 'BLLH — BLOCK LEFT LATERAL MT III', true, 100),
('item_code', 'BLMH — BLOCK LEFT MEDIAL MT III', true, 101),
('item_code', 'BLPS — BLOCK LEFT PROXIMAL SUSPENSOR', true, 102),
('item_code', 'BLSC — BLOCK LEFT SCAPULA', true, 103),
('item_code', 'BRTP — BLOCK R TIBIAL PERONEAL NERVES', true, 104),
('item_code', 'BRFX — BLOCK RIGHT FRONT ABAXIAL', true, 105),
('item_code', 'BRFA — BLOCK RIGHT FRONT ANKLES', true, 106),
('item_code', 'BRFH — BLOCK RIGHT FRONT FOOT', true, 107),
('item_code', 'BRFV — BLOCK RIGHT FRONT HIGH VOLAR', true, 108),
('item_code', 'BRF4 — BLOCK RIGHT FRONT LOW 4', true, 109),
('item_code', 'BRFD — BLOCK RIGHT FRONT PALMAR DIGIT', true, 110),
('item_code', 'BRFP — BLOCK RIGHT FRONT PASTER', true, 111),
('item_code', 'BRFR — BLOCK RIGHT FRONT RING BLOCK', true, 112),
('item_code', 'BRFS — BLOCK RIGHT FRONT SHIN', true, 113),
('item_code', 'BRFT — BLOCK RIGHT FRONT TENDON', true, 114),
('item_code', 'BRHX — BLOCK RIGHT HIND ABAXIAL', true, 115),
('item_code', 'BRHA — BLOCK RIGHT HIND ANKLE', true, 116),
('item_code', 'BRHF — BLOCK RIGHT HIND FOOT', true, 117),
('item_code', 'BRH4 — BLOCK RIGHT HIND LOW 4', true, 118),
('item_code', 'BRHD — BLOCK RIGHT HIND PLANTAR DIGIT', true, 119),
('item_code', 'BRHR — BLOCK RIGHT HIND RING BLOCK', true, 120),
('item_code', 'BRHH — BLOCK RIGHT HOCK', true, 121),
('item_code', 'BRLH — BLOCK RIGHT LATERAL MT III', true, 122),
('item_code', 'BRMH — BLOCK RIGHT MEDIAL MT III', true, 123),
('item_code', 'BRPS — BLOCK RIGHT PROXIMAL SUSPENSOR', true, 124),
('item_code', 'BSIR — BLOCK SACROILINE', true, 125),
('item_code', 'BSHO — BLOCK SHOULDERS', true, 126),
('item_code', 'BTAL — BLOCK TAIL', true, 127),
('item_code', 'BLTP — BLOCK TIBIAL PERONEAL NERVES', true, 128),
('item_code', 'DBLT — BLOOD COLLECTION & TRANSFUSION', true, 129),
('item_code', 'OBYP — BOCA Y PURGANTE', true, 130),
('item_code', 'SBCI — BONE CYST INJECTION', true, 131),
('item_code', 'SBME — BONE MARROW EXTRACTION & INJEC', true, 132),
('item_code', 'BOTOX — BOTOX LAMINITIS TX', true, 133),
('item_code', 'BSNE — BREEDIN SOUNDNESS EXAM', true, 134),
('item_code', 'GBAL — BRONCHO-ALVEOLAR LAVAGE', true, 135),
('item_code', 'ICAC — CALCIUM INFUSION', true, 136),
('item_code', 'OCAP — CAP REMOVAL', true, 137),
('item_code', 'SCAS — CASLICKS', true, 138),
('item_code', 'SCAO — CASLICKS OPENED', true, 139),
('item_code', 'CAST AP — CAST APPLICATION', true, 140),
('item_code', 'CAST RM — CAST REMOVAL', true, 141),
('item_code', 'SCAT — CASTRATION', true, 142),
('item_code', 'ICAP — CATHETER PLACEMENT LONG TERM', true, 143),
('item_code', 'ICAT — CATHETER PLACEMENT TEMPORARY', true, 144),
('item_code', 'DSCP — CERTIFICADO DE SALUD Y PARASIT', true, 145),
('item_code', 'DVAC — CERTIFICADO DE VACUNACION', true, 146),
('item_code', 'CHOK — CHOKE RESOLUTION TX', true, 147),
('item_code', 'ICHP — CHONDROPROTECT INJECTION 5CC', true, 148),
('item_code', 'IHCG — CHORULON INJECTION', true, 149),
('item_code', 'CYTA — CITOLOGY ANTECH LAB.', true, 150),
('item_code', 'ICCT — COENZYME TX', true, 151),
('item_code', 'CMON — COLIC MONITORING HR', true, 152),
('item_code', 'CWUP — COLIC WORK UP', true, 153),
('item_code', 'XCSE — COMPETITION SOUNDNESS EXAM', true, 154),
('item_code', 'IOCDT — CONTRCTURE DEFORMITY TX', true, 155),
('item_code', 'ESLC — CORNEA STAIN LEFT', true, 156),
('item_code', 'ESRC — CORNEA STAIN RIGHT', true, 157),
('item_code', 'FHEF — CORRECTIVE SHOEING BY FARRIER', true, 158),
('item_code', 'FTCS — CORRECTIVE TRIM ONE HOOF', true, 159),
('item_code', 'ICRE — CREATININE INJECCTION', true, 160),
('item_code', 'IRMPF — CREATININE, LACTANASE SOPAN', true, 161),
('item_code', 'OCRP — CRIBBING RINGS PLACEMENT', true, 162),
('item_code', 'SCRY — CRYPTORCHID CASTRATION', true, 163),
('item_code', 'TCSF — CSF TAP', true, 164),
('item_code', 'SDBN — DEEP BRANCH SX', true, 165),
('item_code', 'DHAI — DEEP HORN ARTIFICIAL INSEMINAT', true, 166),
('item_code', 'ODWS — DENTAL WORK & SEDATION', true, 167),
('item_code', 'ODWSRD — DENTAL WORK & SEDATION', true, 168),
('item_code', 'ODWSRP — DENTAL WORK & SEDATION REDUCED', true, 169),
('item_code', 'DW02 — DENTAL WORK 2 YRS OLD', true, 170),
('item_code', 'DW03 — DENTAL WORK 3 YRS OLD', true, 171),
('item_code', 'DW04 — DENTAL WORK 4 YRS OLD', true, 172),
('item_code', 'DW5P — DENTAL WORK 5 YRS PLUS', true, 173),
('item_code', 'ODWRC — DENTAL WORK RACING', true, 174),
('item_code', 'IDPP — DEPO PRO TX', true, 175),
('item_code', 'IDEP — DEPOMEDROL INJECTION 5CC', true, 176),
('item_code', 'W2PF — DEWORMING DOUBLE DOSE PASOFINO', true, 177),
('item_code', 'WPFE — DEWORMING EQUALAN L.', true, 178),
('item_code', 'WDIP — DEWORMING IVERMECTIN PASTE', true, 179),
('item_code', 'WPFP — DEWORMING PYRANTEL', true, 180),
('item_code', 'IDEXF — DEXAMETAZONE INJECTION FOR FOA', true, 181),
('item_code', 'IDEZ — DEXTROSE INFUSION', true, 182),
('item_code', 'DFNA — DIAGNOSTIC FINE NEEDLE ASPIRAT', true, 183),
('item_code', 'XDIM — DIGITAL IMAGE / CONVENTIONAL', true, 184),
('item_code', 'IDYP — DIPYRONE IV, 20CC', true, 185),
('item_code', 'RDIS — DISTOCIA', true, 186),
('item_code', 'DMSO — DOMOSO IV INFUSION (SUERO)', true, 187),
('item_code', 'WPAN2 — DOUBLE DOSE PANACUR DEWORMING', true, 188),
('item_code', 'DABS — DRAIN ABCESS', true, 189),
('item_code', 'DSER — DRAIN SEROMA', true, 190),
('item_code', 'IDHT — DROSERA TX', true, 191),
('item_code', 'FEPS — EA HOOF ELEVATION SYSTEM', true, 192),
('item_code', 'SEBA — ELASTRADOR BAND APPLICATION', true, 193),
('item_code', 'DEKG — ELECTROCARDIOGRAM', true, 194),
('item_code', 'EMFL — EMBRYIO FLUSH I EMBRIO', true, 195),
('item_code', 'EMTF — EMBRYO TRANSFER FEE', true, 196),
('item_code', 'EMER — EMERGENCIA', true, 197),
('item_code', 'GSCO — ENDOSCOPY EXAM', true, 198),
('item_code', 'CENE — ENEMA', true, 199),
('item_code', 'GEES — ENTRAPPED EPIGLOTIS SURGERY', true, 200),
('item_code', 'SENU — ENUCLEATION SURGERY', true, 201),
('item_code', 'FIEUT — EQUISTIN', true, 202),
('item_code', 'IECP — ESTRADIOL INJ.', true, 203),
('item_code', 'IEST — ESTRUMATE INJECTION', true, 204),
('item_code', 'EXSP — EVALUACION X-RAYS, SCOPE & COM', true, 205),
('item_code', 'CEXC — EXPLORATORY CELIOTOMY', true, 206),
('item_code', 'DFBP — FARM CALL BLOOD PHYSICAR FOR E', true, 207),
('item_code', 'FSDR — FEI SIGN & DESCRIPTION REPORT', true, 208),
('item_code', 'FEIV — FEI VACCINE CERTIFICATION', true, 209),
('item_code', 'SXFT — FIJACION CON TORNILLOS', true, 210),
('item_code', 'GSSX — FLAB SINUSTOMY', true, 211),
('item_code', 'SLFA — FLANKER CASTRATION', true, 212),
('item_code', 'OFLZ — FLUCONAZOLE TAB.', true, 213),
('item_code', 'GSFT — FLUSH SINUS', true, 214),
('item_code', 'FWOA — FLUSH WOUND OR ABCES', true, 215),
('item_code', 'FDTX — FOAL DIARREA TREATMENT', true, 216),
('item_code', 'IVPL — FOAL HYPERMUNE PLASMA INFUSION', true, 217),
('item_code', 'FATX — FOOT ABCESS TREATMENT', true, 218),
('item_code', 'FFHC — FREEZE FIRE HOOF CANKER', true, 219),
('item_code', 'FLFH — FREEZE FIRE LEFT FRONT HOOF', true, 220),
('item_code', 'FLFC — FREEZE FIRE LF CANON', true, 221),
('item_code', 'FLFS — FREEZE FIRE LF SPLINT', true, 222),
('item_code', 'FLHS — FREEZE FIRE LH SPLINT', true, 223),
('item_code', 'FRFC — FREEZE FIRE RF CANON', true, 224),
('item_code', 'FRFS — FREEZE FIRE RF SPLINT', true, 225),
('item_code', 'FRHS — FREEZE FIRE RH SPLINT', true, 226),
('item_code', 'FRFH — FREEZE FIRE RIGHT FRONT HOOF', true, 227),
('item_code', 'FRHH — FREEZE FIRE RIGHT HIND HOOF', true, 228),
('item_code', 'FSES — FREEZE FIRE SESAMOID', true, 229),
('item_code', 'FNLF — FREEZE NERVE LEFT FRONT', true, 230),
('item_code', 'FNLH — FREEZE NERVE LEFT HIND', true, 231),
('item_code', 'FNRF — FREEZE NERVE RIGHT FRONT', true, 232),
('item_code', 'FNRH — FREEZE NERVE RIGHT HIND', true, 233),
('item_code', 'GSBX — GASTRIC BIOPSY', true, 234),
('item_code', 'CGLV — GASTRIC LAVAGE', true, 235),
('item_code', 'GTPYFU — GASTROSCOPU FOLLOW UP', true, 236),
('item_code', 'GTPYRC — GASTROSCOPY', true, 237),
('item_code', 'VGEN — GENERAL BANDAGE', true, 238),
('item_code', 'IGOL — GOMENOL TX', true, 239),
('item_code', 'SGTR — GRANULATION TISSUE RESECTION', true, 240),
('item_code', 'GRCT — GRANULOSA CELL TUMOR PANEL', true, 241),
('item_code', 'GPLB — GUTTERAL POUCH BIOPSY (LEFT)', true, 242),
('item_code', 'GPFF — GUTTERAL POUCH FLUSH', true, 243),
('item_code', 'GPRB — GUTTERAL PUCH BIOPSY (RIGHT)', true, 244),
('item_code', 'FAES — HER: ADJUSTABLE ELEVATION SHOE', true, 245),
('item_code', 'FCFC — HER: CANKER FREEZE CAUTERY', true, 246),
('item_code', 'FCPA — HER: CANKER POWDER APPLICATION', true, 247),
('item_code', 'FCRC — HER: CANKER RESECTION', true, 248),
('item_code', 'FCAO — HER: CAUTERIZE FOOT SOLE', true, 249),
('item_code', 'FCHK — HER: CHAPMAN HOSPITAL KIT', true, 250),
('item_code', 'FCFT — HER: CORRECTIVE FOAL TRIM', true, 251),
('item_code', 'FICS — HER: CORRECTIVE SHOEING 1 HOOF', true, 252),
('item_code', 'FEWR — HER: EQUILOX HOOF WALL REPAIR', true, 253),
('item_code', 'FEPT — HER: EQUILOX PATCH', true, 254),
('item_code', 'FEOS — HER: EQUILOX RACING PLATE APPL', true, 255),
('item_code', 'FEOSRC — HER: EQUILOX RACING PLATE APPL', true, 256),
('item_code', 'FEIP — HER: EQUIPACK INSTANT PAD APP.', true, 257),
('item_code', 'FEIPRC — HER: EQUIPACK INSTANT PAD APP.', true, 258),
('item_code', 'FFCS — HER: FARRIER CONSULTATION', true, 259),
('item_code', 'FFCSD — HER: FARRIER CONSULTATION', true, 260),
('item_code', 'FFFT — HER: FOAL FOOT TRIM', true, 261),
('item_code', 'FFHE — HER: FOAL GLUE ON HEEL EXT.', true, 262),
('item_code', 'FGSS — HER: FOAL GLUE SUPPORT SHOE', true, 263),
('item_code', 'FDSS — HER: FOAM PLACEMENT', true, 264),
('item_code', 'FWRK — HER: FOOT WORK', true, 265),
('item_code', 'FSGARC — HER: GLUE ON SHOE APP. PER-F', true, 266),
('item_code', 'FGSD — HER: GLUE SHOE DISP. PER/SHOE', true, 267),
('item_code', 'FGSA — HER: GLUE-ON SHOE APP. PER F', true, 268),
('item_code', 'FQRC — HER: HOOF QUARTER CRACK REPAIR', true, 269),
('item_code', 'HWRW — HER: HOOF WALL RES. WHITE LINE', true, 270),
('item_code', 'FHPA — HER: HOSPITAL PLATE APP.', true, 271),
('item_code', 'FHPC — HER: HOSPITAL PLATE CONS.', true, 272),
('item_code', 'FNBS — HER: NATURAL BAL. SHOE (PAIR)', true, 273),
('item_code', 'FNVS — HER: NO VIBE SHOE PAIR', true, 274),
('item_code', 'FORS — HER: OUTER RING STEEL SHOE', true, 275),
('item_code', 'FSRL — HER: SOFT RIDE LEASE', true, 276),
('item_code', 'SSNP — HER: STREET NAIL PROCEDURE', true, 277),
('item_code', 'FUSA — HER: ULTIMATE SHOES APLICATION', true, 278),
('item_code', 'FVBS — HER: VENOGRAM BILATERAL STUDY', true, 279),
('item_code', 'FVUS — HER: VENOGRAM UNILATERAL STUDY', true, 280),
('item_code', 'SHRE — HERNIA REPAIR', true, 281),
('item_code', 'SHER — HERNIA REPAIR WITH ELASTRATOR', true, 282),
('item_code', 'IHRM — HORMONE INJ.', true, 283),
('item_code', 'IJHM — HORMONE INJECTION', true, 284),
('item_code', 'FHPT — HOSPITAL PLATE TREATMENT', true, 285),
('item_code', 'FHPTRC — HOSPITAL PLATE TREATMENTQ', true, 286),
('item_code', 'BOAR — HOSPITALIZACION', true, 287),
('item_code', 'IHPS — HYRATION PACKAGE', true, 288),
('item_code', 'IZOLT — IMIZOL TX', true, 289),
('item_code', 'OITE — INCISOR TOOTH EXTRACTION', true, 290),
('item_code', 'GILP — INDWELLING CATHETER L G-POUNCH', true, 291),
('item_code', 'GIRP — INDWELLING CATHETER R G-POUNCH', true, 292),
('item_code', 'ILSL — INJECT LEFT SACROILIAC LIG.', true, 293),
('item_code', 'TNEU — INJECT NEUROMA', true, 294),
('item_code', 'IRSL — INJECT RIGHT SACROILIAC LIG.', true, 295),
('item_code', 'IHAB — INJECT SUMMER SORE', true, 296),
('item_code', 'ISLP — INJECT SUSP LIQ P R P', true, 297),
('item_code', 'ILBS — INJECTION LUMBOSACRAL JOINT', true, 298),
('item_code', 'DINS — INSURANCE EXAM', true, 299),
('item_code', 'ISTB — INTERNAL STIFLE LIGAMENT BLIST', true, 300),
('item_code', 'ILAI — INTRA LARINGEAL LEFT ARITHNOID', true, 301),
('item_code', 'IRAI — INTRA LARINGEAL RIGHTARITHNOID', true, 302),
('item_code', 'IMBL — INTRA MUSCULAR BLOOD', true, 303),
('item_code', 'THYT — INTRA-ARTICULAR HYALURONIC ACI', true, 304),
('item_code', 'ILIJ — INTRALESION INJESTION', true, 305),
('item_code', 'IMTX — INTRAMAMMARY TX', true, 306),
('item_code', 'BLIM — INTRAMUSCULAR BLOOD INJECTION', true, 307),
('item_code', 'GINF — INTRANASAL FLU-VAC', true, 308),
('item_code', 'GITS — INTRATRACHEAL SAMPLE', true, 309),
('item_code', 'IRAPF1 — IRAP FOLLOW UP #1', true, 310),
('item_code', 'IRAPF2 — IRAP FOLLOW UP #2', true, 311),
('item_code', 'IRAPF3 — IRAP FOLLOW UP #3', true, 312),
('item_code', 'IRAP — IRAP HARVESTIN INTRARTICULAR', true, 313),
('item_code', 'IRAPT — IRAP TAP', true, 314),
('item_code', 'PJCP — JOCKEY CLUB PAPERS FILLED', true, 315),
('item_code', 'JTFL — JOINT FLUSH', true, 316),
('item_code', 'JTFLRC — JOINT FLUSH', true, 317),
('item_code', 'DLAM — LAMENESS EXAM', true, 318),
('item_code', 'DLAMW — LAMENESS EXAM', true, 319),
('item_code', 'LCYF — LAMINITIS CONSULT. YEARLY FEE', true, 320),
('item_code', 'XLAMDP — LAMINITIS X-RAY & OBLIQUES', true, 321),
('item_code', 'LAIN — LATE ARTIFICIAL INSEMINATION', true, 322),
('item_code', 'ILEG — LEGEND INJECTION', true, 323),
('item_code', 'ILYM — LYMPHOMYOSOT TX', true, 324),
('item_code', 'BMLK — MACKAY LEFT KNEE', true, 325),
('item_code', 'BMRK — MACKAY RIGHT KNEE', true, 326),
('item_code', 'BMCR — MACKAY''S RIGHT STIFLE', true, 327),
('item_code', 'BMLC — MACKAY''S STIFLE', true, 328),
('item_code', 'OMFR — MANDIBULAR FRACTURE REPAIR', true, 329),
('item_code', 'OPCX — MANUAL OPENING OF THE CERVIX', true, 330),
('item_code', 'SMPL — MEDIAL PATELLAR LIG DES. LEFT', true, 331),
('item_code', 'SMPR — MEDIAL PATELLAR LIG DES.RIGHT', true, 332),
('item_code', 'IMCHRC — MICROCHIP IMPLANTATION', true, 333),
('item_code', 'PHYM — MONITOREO FISICO POR HORA', true, 334),
('item_code', 'GSTM — MYECTOMY STERNOTHYROID', true, 335),
('item_code', 'GNSC — NASAL SWAB CULTURE', true, 336),
('item_code', 'NGPN — NASOGASTRIC PANACURE', true, 337),
('item_code', 'ONGH — NASOGASTRIC TREATMENT', true, 338),
('item_code', 'ENLD — NASOLACRIMAL DUCT FLUSH', true, 339),
('item_code', 'NECW — NECROPSY', true, 340),
('item_code', 'NECF — NECROPSY WITH REPORT (FULL)', true, 341),
('item_code', 'NECK — NECROPSY WITH REPORT FULL', true, 342),
('item_code', 'NECP — NECROPSY WITH REPORT PARTIAL', true, 343),
('item_code', 'PNEU — NEUROLOGIC EXAM', true, 344),
('item_code', 'EOBL — OPHTHALMIC BLOCK', true, 345),
('item_code', 'EOTX — OPHTHALMIC TX', true, 346),
('item_code', 'FOPA — ORTHO PACK APPLICATION', true, 347),
('item_code', 'OSPHOS — OSPHOS TREATMENT', true, 348),
('item_code', 'SOTX — OSTEOSTIXIS', true, 349),
('item_code', 'IOVU — OVUPLANT INJECTION', true, 350),
('item_code', 'GPWC — PHARYNGCOL WASH CULTURE', true, 351),
('item_code', 'PERESP — PHYSICAL & RADIOGRAPHIC EVALUA', true, 352),
('item_code', 'PCUP — PHYSICAL CHECK UP', true, 353),
('item_code', 'PHEX — PHYSICAL EXAM', true, 354),
('item_code', 'PHYE — PHYSICAL EXAM', true, 355),
('item_code', 'PHEXT — PHYSICAL EXAM & TAPS', true, 356),
('item_code', 'PHEF — PHYSICAL EXAM FOALS', true, 357),
('item_code', 'PKSA — PINFIRE KNEE, SHINS & ANKLES', true, 358),
('item_code', 'PFOA — PINFIRE ONLY ANKLES', true, 359),
('item_code', 'PFCM — PINFIRE SHINS & ANKLES', true, 360),
('item_code', 'PFCMRC — PINFIRE SHINS & ANKLES', true, 361),
('item_code', 'PFOC — PINFIRE SHINS ONLY', true, 362),
('item_code', 'PFSP — PINFIRE SPLINTS', true, 363),
('item_code', 'SPLR — PLATE REMOVAL', true, 364),
('item_code', 'PBFL — POST BREEDING FLUSH & OXYTOCIN', true, 365),
('item_code', 'PBFI — POST BREEDING FLUSH W/IODINE', true, 366),
('item_code', 'PBFD — POST-BREEDING FLUSH W/DMSO', true, 367),
('item_code', 'PPPE — PREPURCHASE EXAM', true, 368),
('item_code', 'PPPEBW — PREPURCHASE EXAM W/BLOOD WORK', true, 369),
('item_code', 'OPRV — PREVENTCAL', true, 370),
('item_code', 'PRPT — PRP TREATMENT', true, 371),
('item_code', 'OPUR — PURGANTE', true, 372),
('item_code', 'PBFA — PWT BREEDING FLUSH W/ ANTIBIOT', true, 373),
('item_code', 'XRSE — RACING SOUNDENESS EXAM', true, 374),
('item_code', 'XRSED — RACING SOUNDENESS EXAM DIGITAL', true, 375),
('item_code', 'RXEX — RADIGRAPHIC EVALUATION', true, 376),
('item_code', 'RERP — RADIOGRAPHIC EVA O FULL SET RP', true, 377),
('item_code', 'RERPK — RADIOGRAPHIC EVA O FULL SET RP', true, 378),
('item_code', 'REFS — RADIOGRAPHIC EVAL. OF FULL SET', true, 379),
('item_code', 'REFSK — RADIOGRAPHIC EVAL. OF FULL SET', true, 380),
('item_code', 'DRCT — RECTAL EXAM', true, 381),
('item_code', 'USRE — RECTAL ULTRASOUND', true, 382),
('item_code', 'RDTW — REDUCE TWIN PREGNACY', true, 383),
('item_code', 'SRLP — REGIONAL LIMB PERFUSION', true, 384),
('item_code', 'USUS — REPRODUCTIVE ULTRASOUND', true, 385),
('item_code', 'RSTH — RESPIRATORY THERAPY', true, 386),
('item_code', 'RSTX — RESPIRATORY TREATMENT', true, 387),
('item_code', 'VRJD — ROBERT JONES DRESSING', true, 388),
('item_code', 'VRJDRC — ROBERT JONES DRESSING', true, 389),
('item_code', 'SSCH — SCHIRROUS CORD CORRECTION', true, 390),
('item_code', 'SSRR — SCRE REMOVAL', true, 391),
('item_code', 'SFDR — SCREW FIXACION DR PHYSIS', true, 392),
('item_code', 'SFFD — SCROTAL FLUSH', true, 393),
('item_code', 'PREP — SELECTION, PHYSICAL EVALUATION', true, 394),
('item_code', 'ASFL — SHAVE FRONT LEG', true, 395),
('item_code', 'ASHL — SHAVE HIND LEG', true, 396),
('item_code', 'SHEA — SHEATH CLEANING', true, 397),
('item_code', 'SSPS — SHIN PERIOSTEAL SCRATCHING', true, 398),
('item_code', 'SWLHGT — SHOCKWAVE LH GASTROCNEMIUS', true, 399),
('item_code', 'SWRHGT — SHOCKWAVE RH GASTROCNEMIUS', true, 400),
('item_code', 'SWT21 — SHOCKWAVE TX', true, 401),
('item_code', 'SWTX — SHOCKWAVE TX', true, 402),
('item_code', 'FSRV — SHOE REPLACEMENT VET', true, 403),
('item_code', 'DSFS — SIGNALMENT FORM', true, 404),
('item_code', 'GSFS — SINUS FLUSH SALINE', true, 405),
('item_code', 'GSFP — SINUS FLUSH SYSTEMS PLACEMENT', true, 406),
('item_code', 'SMRE — SKIN MASS REMOVAL', true, 407),
('item_code', 'SWRR — SKIN MASS REMOVAL', true, 408),
('item_code', 'DSPB — SKIN PUNCH BIOPSY', true, 409),
('item_code', 'SMAR — SMALL MASS REMOVAL', true, 410),
('item_code', 'EMCO — SOUNDNESS EXAM', true, 411),
('item_code', 'DVSE — SPECULUM EXAM', true, 412),
('item_code', 'VSPL — SPLINT BANDAGE', true, 413),
('item_code', 'VSPLSU — SPLINT BANDAGE & SUPPORT BANDA', true, 414),
('item_code', 'SSPP — SPLINT BONE REMOVAL DISTAL', true, 415),
('item_code', 'SSPL — SPLINT BONE REMOVAL SEGMENTAL', true, 416),
('item_code', 'FSCA — STEWARD CLOG APPICATION', true, 417),
('item_code', 'STIT — STITCHING', true, 418),
('item_code', 'ISTG — STRANGLES VACCINE', true, 419),
('item_code', 'IJSQ — SUBCUTANEOUS INJECTION', true, 420),
('item_code', 'GSEC — SUB-EPIGLOTIC CYTS SURGERY', true, 421),
('item_code', 'ESPL — SUBPALPEBRAL LAVAGE SET UP', true, 422),
('item_code', 'SELD — SUP. CHECK LIGAMENT DESMOTOMY', true, 423),
('item_code', 'VLFS — SUPPORT BANDAGE LF DISTAL LIMB', true, 424),
('item_code', 'VLHS — SUPPORT BANDAGE LH DISTAL LIMB', true, 425),
('item_code', 'VRFS — SUPPORT BANDAGE RF DISTAL LIMB', true, 426),
('item_code', 'VRHS — SUPPORT BANDAGE RH DISTAL LIMB', true, 427),
('item_code', 'SWRM — SURGERY WART REMOVAL', true, 428),
('item_code', 'SURM — SUTURE REMOVAL', true, 429),
('item_code', 'VSWE — SWEAT BANDAGE', true, 430),
('item_code', 'VSWF — SWEAT BANDAGE FULL LEG', true, 431),
('item_code', 'TCHO — TAP CAPPED HOCK', true, 432),
('item_code', 'TCEJ — TAP COLCEGEAL JOINTS', true, 433),
('item_code', 'THYG — TAP HYGROMA', true, 434),
('item_code', 'TLEC — TAP L EXTENSOR RADIALIS SHEATH', true, 435),
('item_code', 'TLCC — TAP LEFT CARPAL CANAL', true, 435),
('item_code', 'TLCE — TAP LEFT COMMON DIGITAL EXTENS', true, 437),
('item_code', 'TLDS — TAP LEFT DDFT SHEATH', true, 438),
('item_code', 'TLIT — TAP LEFT DISTAL INTERSAL JNT.', true, 439),
('item_code', 'TLDI — TAP LEFT DISTAL INTERTARSAL', true, 440),
('item_code', 'TLEL — TAP LEFT ELBOW', true, 441),
('item_code', 'TLST — TAP LEFT FEMORO PATELLAR JOINT', true, 442),
('item_code', 'TLFA — TAP LEFT FRONT ANKLE JNT', true, 443),
('item_code', 'TLFC — TAP LEFT FRONT COFFIN JNT', true, 444),
('item_code', 'TLFES — TAP LEFT FRONT EXTENSOR SHEATH', true, 445),
('item_code', 'TLFL — TAP LEFT FRONT LIGAMENT', true, 446),
('item_code', 'TLFNB — TAP LEFT FRONT NAVICULAR BURSA', true, 447),
('item_code', 'TLFP — TAP LEFT FRONT PASTERN JNT', true, 448),
('item_code', 'TLFT — TAP LEFT FRONT TENDON', true, 449),
('item_code', 'TLHA — TAP LEFT HIND ANKLE JNT', true, 450),
('item_code', 'TLHC — TAP LEFT HIND COFFIN JNT', true, 451),
('item_code', 'TLHL — TAP LEFT HIND LIGAMENT', true, 452),
('item_code', 'TLHP — TAP LEFT HIND PASTERN JNT', true, 453),
('item_code', 'TLHT — TAP LEFT HIND TENDON', true, 454),
('item_code', 'TLHJ — TAP LEFT HIP JOINT', true, 455),
('item_code', 'TLHO — TAP LEFT HOCK', true, 456),
('item_code', 'TLIC — TAP LEFT INTERCARPAL JNT', true, 457),
('item_code', 'TLLF — TAP LEFT LATERAL FEMORO TIBIAL', true, 458),
('item_code', 'TLMF — TAP LEFT MEDIAL FEMORO TIBIAL', true, 459),
('item_code', 'TLNB — TAP LEFT NAVICULAR BURSA', true, 460),
('item_code', 'TLRC — TAP LEFT RADIOCARPAL JNT', true, 461),
('item_code', 'TLSL — TAP LEFT REMORO PATELLAR JOINT', true, 462),
('item_code', 'TLSI — TAP LEFT SACRO ILIAC JOINT', true, 463),
('item_code', 'TSHL — TAP LEFT SHEATH', true, 464),
('item_code', 'TLSH — TAP LEFT SHOULDER JNT', true, 465),
('item_code', 'TLTS — TAP LEFT TARSAL SHEATH', true, 466),
('item_code', 'TLTC — TAP LEFT TARSOCURRAL JOINT', true, 467),
('item_code', 'TLTM — TAP LEFT TEMPORO-MANDIBULAR JO', true, 468),
('item_code', 'TREC — TAP R EXTENSOR RADIALIS SHEATH', true, 469),
('item_code', 'TRFES — TAP RIGH FRONT EXTENSOR SHEATH', true, 470),
('item_code', 'TRCC — TAP RIGHT CARPAL CANAL', true, 471),
('item_code', 'TRCE — TAP RIGHT COMMON DIGITAL EXTEN', true, 472),
('item_code', 'TRDS — TAP RIGHT DDFT SHEATH', true, 473),
('item_code', 'TRDI — TAP RIGHT DISTAL INTERTARSAL', true, 474),
('item_code', 'TRIT — TAP RIGHT DISTAL INTERTARSAL J', true, 475),
('item_code', 'TREL — TAP RIGHT ELBOW JNT', true, 476),
('item_code', 'TRST — TAP RIGHT FEMORO PATELLAR JOIN', true, 477),
('item_code', 'TRFA — TAP RIGHT FRONT ANKLE JNT', true, 478),
('item_code', 'TRFC — TAP RIGHT FRONT COFFIN JNT', true, 479),
('item_code', 'TRFL — TAP RIGHT FRONT LIGAMENT', true, 480),
('item_code', 'TRFP — TAP RIGHT FRONT PASTERN JNT', true, 481),
('item_code', 'TRFT — TAP RIGHT FRONT TENDON', true, 482),
('item_code', 'TRHA — TAP RIGHT HIND ANKLE JNT', true, 483),
('item_code', 'TRHC — TAP RIGHT HIND COFFIN JNT', true, 484),
('item_code', 'TRHL — TAP RIGHT HIND LIGAMENT', true, 485),
('item_code', 'TRHP — TAP RIGHT HIND PASTERN JNT', true, 486),
('item_code', 'TRHT — TAP RIGHT HIND TENDON', true, 487),
('item_code', 'TRHJ — TAP RIGHT HIP JOINT', true, 488),
('item_code', 'TRHO — TAP RIGHT HOCK', true, 489),
('item_code', 'TRIC — TAP RIGHT INTERCARPAL JNT', true, 490),
('item_code', 'TRLF — TAP RIGHT LATERAL FEMORO TIBIA', true, 491),
('item_code', 'TRMF — TAP RIGHT MEDIAL FEMORO TIBIAL', true, 492),
('item_code', 'TRNB — TAP RIGHT NAVICULAR BURSA', true, 493),
('item_code', 'TRRC — TAP RIGHT RADIOCARPAL JNT', true, 494),
('item_code', 'TRSI — TAP RIGHT SACRO ILIAC JOINT', true, 495),
('item_code', 'TSHR — TAP RIGHT SHEATH', true, 496),
('item_code', 'TRSH — TAP RIGHT SHOULDER JNT', true, 497),
('item_code', 'TRTS — TAP RIGHT TARSAL SHEATH', true, 498),
('item_code', 'TRTC — TAP RIGHT TARSOCURRAL JOINT', true, 499),
('item_code', 'TRTM — TAP RIGHT TEMPORO-MANDIBULAR J', true, 500),
('item_code', 'TRFNB — TAP RIGHTFRONT NAVICULAR BURSA', true, 501),
('item_code', 'TDSB — TAP SHOE BOIL TREATMENT', true, 502),
('item_code', 'STCA — TARSAL CHEMICAL ARTHRODESIS', true, 503),
('item_code', 'STFA — TARSAL FACILITATED ARTHRODESIS', true, 504),
('item_code', 'OTFF — TEETH FLOAT', true, 505),
('item_code', 'OTFD — TEETH FLOAT DREMEL TOOL', true, 506),
('item_code', 'STSS — TENDOM SPLITTING', true, 507),
('item_code', 'SLDT — TENOTOMY LEFT DFT', true, 508),
('item_code', 'SRDT — TENOTOMY RIGHT DFT', true, 509),
('item_code', 'GSTT — TENOTOMY STERNOTHYROID', true, 510),
('item_code', 'IPRP — TERAPIA REGENERATIVA POR INYEC', true, 511),
('item_code', 'THLC — THORACOCENTESIS LEFT', true, 512),
('item_code', 'THRC — THORACOCENTESIS RIGHT', true, 513),
('item_code', 'GTFL — THROAT FLUSH', true, 514),
('item_code', 'GTSX — TIEBACK SURGERY', true, 515),
('item_code', 'OTOL — TOLTRAZURL TX', true, 516),
('item_code', 'OTEX — TOOTH EXTRACTION', true, 517),
('item_code', 'LTPP — TOTAL PROTEIN DETERMINATION', true, 518),
('item_code', 'DTPE — TOTAL PROTEIN EVALUATION', true, 519),
('item_code', 'DTPT — TOTAL PROTEIN IN HOUSE', true, 520),
('item_code', 'GTPS — TRACHEOTOMY PERMANENT SURGERY', true, 521),
('item_code', 'GTCS — TRACHEOTOMY SURGERY', true, 522),
('item_code', 'GTEB — TRANSENDOSCOPIC', true, 523),
('item_code', 'CTRA — TRANSFUNATION', true, 524),
('item_code', 'COUR — TRANSPORTE DE SEMEN', true, 525),
('item_code', 'GTTC — TRANSTRACHEAL CULTURE', true, 526),
('item_code', 'GTTW — TRANSTRACHEAL WASH', true, 527),
('item_code', 'TXMT — TRATAMIENTO DE MASTITIS', true, 528),
('item_code', 'ITRA — TRAUMEEL THREATMENT', true, 529),
('item_code', 'TRPL — TREATMENT OF RETAINED PLACENTA', true, 530),
('item_code', 'USAB — ULTRASOUND ABDOMEN', true, 531),
('item_code', 'USCH — ULTRASOUND CHEST', true, 532),
('item_code', 'USEV — ULTRASOUND EVALUATION', true, 533),
('item_code', 'USEY — ULTRASOUND EYE', true, 534),
('item_code', 'USHD — ULTRASOUND HEAD', true, 535),
('item_code', 'USHT — ULTRASOUND HEART', true, 536),
('item_code', 'USIN — ULTRASOUND INTERPRETATION', true, 537),
('item_code', 'USLG — ULTRASOUND LEGS', true, 538),
('item_code', 'USLGRC — ULTRASOUND LEGS', true, 539),
('item_code', 'USMA — ULTRASOUND MASS', true, 540),
('item_code', 'USNE — ULTRASOUND NECK', true, 541),
('item_code', 'USPE — ULTRASOUND PELVIS', true, 542),
('item_code', 'USUN — ULTRASOUND REP. TRACT NO CHARG', true, 543),
('item_code', 'USUT — ULTRASOUND REPRODUCTIVE TRACT', true, 544),
('item_code', 'USTES — ULTRASOUND TESTICULES', true, 545),
('item_code', 'USVN — ULTRASOUND VEINS', true, 546),
('item_code', 'UCTX — UMBILICAL CORD TREATMENT', true, 547),
('item_code', 'DUCA — URETRAL CATHETERIZATION', true, 548),
('item_code', 'DUTI — UTERINE INFUSION', true, 549),
('item_code', 'UIAB — UTERINE INFUSION ANTIBIOTICS', true, 550),
('item_code', 'UIAM — UTERINE INFUSION ANTIFUNGAL', true, 551),
('item_code', 'UIAC — UTERINE INFUSION CEFALEOXIN', true, 552),
('item_code', 'UIAF — UTERINE INFUSION OF ANTIFUNGAL', true, 553),
('item_code', 'UULV — UTERINE LAVAGE', true, 554),
('item_code', 'IVAC — VACUNAS Y CERTIFICADO', true, 555),
('item_code', 'DVST — VESICULAR STOMATITIS TEST', true, 556),
('item_code', 'DVEP — VIRAL ENCEPHALITIS PANEL', true, 557),
('item_code', 'DFCL — VISITA', true, 558),
('item_code', 'DFPH — VISITA Y EXAMEN FISICO', true, 559),
('item_code', 'SWEL — WART ELASTRATION', true, 560),
('item_code', 'WCEV — WEANLING CONF. EVALUATION', true, 561),
('item_code', 'WTTX — WEIGHT TX', true, 562),
('item_code', 'IWNV — WEST NILE 1CC', true, 563),
('item_code', 'DWNV — WEST NILE VIRUS TEST', true, 564),
('item_code', 'DWBL — WESTERN BLOOD TEST', true, 565),
('item_code', 'OWBT — WHITE BLEEDING TREATMENT', true, 566),
('item_code', 'DWBC — WHITE BLLOD CELL COUNT', true, 567),
('item_code', 'DWBCRC — WHITE BLLOD CELL COUNT', true, 568),
('item_code', 'OWTE — WOLF TEETH EXTRACTION', true, 569),
('item_code', 'WDTX — WOUND TX', true, 570),
('item_code', 'WDTXRC — WOUND TX', true, 571),
('item_code', 'XRAB — X-RAY ABDOMEN', true, 572),
('item_code', 'XALX — X-RAY AP L KNEE', true, 573),
('item_code', 'XALXD — X-RAY AP L KNEE DIGITAL', true, 574),
('item_code', 'XARX — X-RAY AP R KNEE', true, 575),
('item_code', 'XARXD — X-RAY AP R KNEE DIGITAL', true, 576),
('item_code', 'XBCS — X-RAY BILAT. C III SKYLINE DIG', true, 577),
('item_code', 'XBCSD — X-RAY BILATERAL C III SKYL DIG', true, 578),
('item_code', 'XRCH — X-RAY CHEST', true, 579),
('item_code', 'XCST — X-RAY CONTRAST STUDY', true, 580),
('item_code', 'XCSTD — X-RAY CONTRAST STUDY DIGITAL', true, 581),
('item_code', 'XXXS — X-RAY EVALUATION SINGLE JOINT', true, 582),
('item_code', 'XXXD — X-RAY EVALUATION SOUNDNESS EXA', true, 583),
('item_code', 'XXXX — X-RAY EVALUATION SOUNDNESS EXM', true, 584),
('item_code', 'XAHS — X-RAY FETLOCK HANGING SHOT', true, 585),
('item_code', 'XAHSD — X-RAY FETLOCK HANGING SHOT DIG', true, 586),
('item_code', 'XHED — X-RAY HEAD', true, 587),
('item_code', 'XHEDD — X-RAY HEAD DIGITAL', true, 588),
('item_code', 'XRHP — X-RAY HIND PASTERN', true, 589),
('item_code', 'XHSH — X-RAY HOCK SKYLINE-TUBER CALCA', true, 590),
('item_code', 'XHSX — X-RAY HOCK SKYLINE-TUBER CALCA', true, 591),
('item_code', 'XHEBD — X-RAY HOOF BAL EVALUATION DIG', true, 592),
('item_code', 'XHEB — X-RAY HOOF BALANCE EVALUATION', true, 593),
('item_code', 'XLFCD — X-RAY L FRONT CANON BONE DIG', true, 594),
('item_code', 'XLFPD — X-RAY L FRONT PASTERN DIGITAL', true, 595),
('item_code', 'XLAM — X-RAY LAMINITIS SHOT', true, 596),
('item_code', 'XLAMD — X-RAY LAMINITIS SHOT DIG', true, 597),
('item_code', 'XLEL — X-RAY LEFT ELBOW', true, 598),
('item_code', 'XLELD — X-RAY LEFT ELBOW DIGITAL', true, 599),
('item_code', 'XLFA — X-RAY LEFT FRONT ANKLE', true, 600),
('item_code', 'XLFAD — X-RAY LEFT FRONT ANKLE DIG', true, 601),
('item_code', 'XLFC — X-RAY LEFT FRONT CANON BONE', true, 602),
('item_code', 'XLFF — X-RAY LEFT FRONT FOOT', true, 603),
('item_code', 'XLFFD — X-RAY LEFT FRONT FOOT DIGITAL', true, 604),
('item_code', 'XLFS — X-RAY LEFT FRONT SPLINTS', true, 605),
('item_code', 'XLFSD — X-RAY LEFT FRONT SPLINTS DIG', true, 606),
('item_code', 'XLHA — X-RAY LEFT HIND ANKLE', true, 607),
('item_code', 'XLHAD — X-RAY LEFT HIND ANKLE DIGITAL', true, 608),
('item_code', 'XLHC — X-RAY LEFT HIND CANON BONE', true, 609),
('item_code', 'XLHCD — X-RAY LEFT HIND CANON BONE DIG', true, 610),
('item_code', 'XLHF — X-RAY LEFT HIND FOOT',
