-- Seed 40 test horses for race day testing
-- Run this migration to populate the horses table with test data
INSERT INTO horses (name, microchip, registration, color, status, owner, trainer, gender) VALUES
('Rayo de Luz', 'MIC001', 'REG001', 'Bay', 'active', 'Owner A', 'Trainer 1', 'M'),
('Viento Fuerte', 'MIC002', 'REG002', 'Chestnut', 'active', 'Owner B', 'Trainer 2', 'M'),
('Bella Noche', 'MIC003', 'REG003', 'Black', 'active', 'Owner C', 'Trainer 1', 'F'),
('Trueno Veloz', 'MIC004', 'REG004', 'Bay', 'active', 'Owner D', 'Trainer 3', 'M'),
('Luna Plateada', 'MIC005', 'REG005', 'Gray', 'active', 'Owner E', 'Trainer 2', 'F'),
('Fuego Ardiente', 'MIC006', 'REG006', 'Chestnut', 'active', 'Owner F', 'Trainer 1', 'M'),
('Sombra Negra', 'MIC007', 'REG007', 'Black', 'active', 'Owner G', 'Trainer 4', 'M'),
('Estrella Blanca', 'MIC008', 'REG008', 'Gray', 'active', 'Owner H', 'Trainer 3', 'F'),
('Galope Libre', 'MIC009', 'REG009', 'Bay', 'active', 'Owner I', 'Trainer 2', 'M'),
('Salto Alto', 'MIC010', 'REG010', 'Chestnut', 'active', 'Owner J', 'Trainer 1', 'M'),
('Corriente Rápida', 'MIC011', 'REG011', 'Black', 'active', 'Owner K', 'Trainer 5', 'F'),
('Pista Dorada', 'MIC012', 'REG012', 'Bay', 'active', 'Owner L', 'Trainer 3', 'M'),
('Viento del Norte', 'MIC013', 'REG013', 'Gray', 'active', 'Owner M', 'Trainer 2', 'F'),
('Fuerte Corazón', 'MIC014', 'REG014', 'Chestnut', 'active', 'Owner N', 'Trainer 4', 'M'),
('Campeón Justo', 'MIC015', 'REG015', 'Black', 'active', 'Owner O', 'Trainer 1', 'M'),
('Brisa Suave', 'MIC016', 'REG016', 'Bay', 'active', 'Owner P', 'Trainer 5', 'F'),
('Destello Rapido', 'MIC017', 'REG017', 'Chestnut', 'active', 'Owner Q', 'Trainer 3', 'M'),
('Victoria Segura', 'MIC018', 'REG018', 'Gray', 'active', 'Owner R', 'Trainer 2', 'F'),
('Orgullo del Turf', 'MIC019', 'REG019', 'Black', 'active', 'Owner S', 'Trainer 4', 'M'),
('Gloria Eterna', 'MIC020', 'REG020', 'Bay', 'active', 'Owner T', 'Trainer 1', 'F'),
('Trueno Blanco', 'MIC021', 'REG021', 'Gray', 'active', 'Owner U', 'Trainer 5', 'M'),
('Relámpago Rojo', 'MIC022', 'REG022', 'Chestnut', 'active', 'Owner V', 'Trainer 2', 'M'),
('Sueño Cumplido', 'MIC023', 'REG023', 'Black', 'active', 'Owner W', 'Trainer 3', 'F'),
('Arco Iris', 'MIC024', 'REG024', 'Bay', 'active', 'Owner X', 'Trainer 1', 'M'),
('Piedra Firme', 'MIC025', 'REG025', 'Chestnut', 'active', 'Owner Y', 'Trainer 4', 'F'),
('Nube Blanca', 'MIC026', 'REG026', 'Gray', 'active', 'Owner Z', 'Trainer 5', 'M'),
('Cristal Claro', 'MIC027', 'REG027', 'Black', 'active', 'Owner AA', 'Trainer 2', 'M'),
('Diamante Puro', 'MIC028', 'REG028', 'Bay', 'active', 'Owner AB', 'Trainer 3', 'F'),
('Espíritu Libre', 'MIC029', 'REG029', 'Chestnut', 'active', 'Owner AC', 'Trainer 1', 'M'),
('Ala de Águila', 'MIC030', 'REG030', 'Gray', 'active', 'Owner AD', 'Trainer 4', 'F'),
('Caballería Real', 'MIC031', 'REG031', 'Black', 'active', 'Owner AE', 'Trainer 5', 'M'),
('Monarca del Turf', 'MIC032', 'REG032', 'Bay', 'active', 'Owner AF', 'Trainer 2', 'M'),
('Príncipe Negro', 'MIC033', 'REG033', 'Black', 'active', 'Owner AG', 'Trainer 3', 'M'),
('Duque Gris', 'MIC034', 'REG034', 'Gray', 'active', 'Owner AH', 'Trainer 1', 'M'),
('Conde de Oro', 'MIC035', 'REG035', 'Chestnut', 'active', 'Owner AI', 'Trainer 4', 'M'),
('Barón Veloz', 'MIC036', 'REG036', 'Bay', 'active', 'Owner AJ', 'Trainer 5', 'M'),
('Marqués del Galope', 'MIC037', 'REG037', 'Black', 'active', 'Owner AK', 'Trainer 2', 'M'),
('Conde Oscuro', 'MIC038', 'REG038', 'Chestnut', 'active', 'Owner AL', 'Trainer 3', 'M'),
('Duquesa Blanca', 'MIC039', 'REG039', 'Gray', 'active', 'Owner AM', 'Trainer 1', 'F'),
('Reina del Turf', 'MIC040', 'REG040', 'Bay', 'active', 'Owner AN', 'Trainer 4', 'F')
ON CONFLICT (microchip) DO NOTHING;
